### ISSUE TITLE
Can't change color of background

### ISSUE THREAD

**Issue by HeyJonny** [janraasch/hugo-scroll#1]
Hello,

I am not quite sure, if this is an issue, but I am not able to change the color of the background (default red) oder the buttons. Could you please explain me, how I can achieve this?

Best regards!

**Comment by janraasch** [comment]
Hi @HeyJonny, thank you for getting in-touch 👋🏻.

> I am not quite sure, if this is an issue, , but I am not able to change the color of the background (default red) oder the buttons

The solutions to your problem depends a lot on your technical or not so technical background 😛 😁.

Currently there is no »simple«-way to do this. I was thinking about adding some `variables.scss` so these values / colors could be overwritten rather easily. Something like what's shown in the docs here: https://gohugo.io/hugo-pipes/resource-from-template/. That's future work though...

To solve the problem at hand what would work is that you add a `custom_head.html` to your `layouts/partials`-directory. If you started from the `exampleSite` on this repo, you should already have such a file. In there you can add a `<style>`-tag to overwrite the colors like so

```
<style>
    /* Links */
    a:hover {
        color: #b6b84c;
    }

    /* Header Buttons on Startpage */
    a.btn {
        color: white;
         background-color: #ced067;
    }
    a.btn:hover {
         background-color: #b6b84c;
    }

    /* Scroll Menu on Startpage */
    a.fn-item.active {
         color: #b6b84c;
    }
    a.fn-item:hover {
         color: #ced067;
    }

    /* Content / Sections */
    .post-holder.odd {
         background: #B80135;
         color: white;
    }
    .post-holder {
         background: #f2efe8;
    }
    body {
         color: #3A4145;
    }

    /* Footer */
    .site-footer {
         color: #BBC7CC;
         background-color: #22343A;
    }
</style>
```

With this the buttons on the header look like:

![Screenshot 2020-08-11 at 09 15 43](https://user-images.githubusercontent.com/425211/89868562-487cf880-dbb3-11ea-9d62-c56249679562.png)

Let me know, if this helps 😇 😁.

Kind regards,
Jan

**Comment by HeyJonny** [comment]
It works! Thank you for the easy description :) 

Thanks!!
Pascal

**Comment by janraasch** [comment]
Sure, no problem. Let me know once you publish your site, I'd love to see what you did with the theme 💇‍♂️ 😄 .

Have a great weekend 👋 ,
Jan
