### ISSUE TITLE
Extra space in icon shortcode

### ISSUE THREAD

**Issue by metbril** [janraasch/hugo-scroll#12]
I use the icon shortcode to display a row of linked icons only. I use this format:

    [{{<icon class="fa fa-github">}}](https://github.com/metbril)
    [{{<icon class="fa fa-gitlab">}}](https://gitlab.com/metbril)

When put in a row, an extra whitespace character is added after each icon. This shows as an underscore, which is ugly.

<img width="446" alt="afbeelding" src="https://user-images.githubusercontent.com/559346/99418072-e7c03300-28fa-11eb-9204-c025027d0d3b.png">

This underscore can be removed by removing the blank line in the shortcode. I will submit a tiny PR for this.

**Comment by janraasch** [comment]
Hi @metbril, thank you so much 💝. 

This is a very nice catch and a nice *learning* of how shortcuts work for me 👍. 

The behavior should be fixed with https://github.com/janraasch/hugo-scroll/commit/789ff52256b8f232710f280c5a992178d98e11c1. 

Enjoy 👋🏻,
Jan.
