### ISSUE TITLE
Downloadable font: no supported format found (font-family: "FontAwesome"

### ISSUE THREAD

**Issue by Talisker69** [janraasch/hugo-scroll#17]
Hi,
First of all thanks for your theme HuGoScroll.
After publish my pages with Hugo and your themes I 'have the following error with Firefox on my web site : downloadable font: no supported format found (font-family: "FontAwesome" style:normal weight:400 stretch:100 src index:5) source: (end of source list) .
All Icones (from Font-awesome) on the pages are not dispayed and replaced by a square.
Have you an idea of that come from ?
Regards,
JC

**Comment by janraasch** [comment]
Hi @Talisker69, thank you for getting in touch 🤝. Nice to meet you 😁.

> First of all thanks for your theme HuGoScroll.

I am glad you like it ☺️.

> After publish my pages with Hugo and your themes I 'have the following error with Firefox on my web site : downloadable font: no supported format found (font-family: "FontAwesome" style:normal weight:400 stretch:100 src index:5) source: (end of source list) .
All Icones (from Font-awesome) on the pages are not dispayed and replaced by a square.
Have you an idea of that come from ?

I would assume it is a mixed content problem, see https://support.mozilla.org/en-US/kb/mixed-content-blocking-firefox. E.g. this could happen, when you access the site via `https://...` (SSL), but some assets (e.g. fonts) are loaded via `http://` (non-SSL).

Can you share your `baseURL`-setting and the full `url` where you try to access the page? Then we can check if my assumption is correct and we can have a look at how to fix this.

**Comment by Talisker69** [comment]
baseURL = "https://liberezvosressources.fr"
Site : https://www.liberezvosressources.fr/

**Comment by janraasch** [comment]
Thank you.

Here's a screenshot from the JavaScript console:

![Screenshot 2020-12-11 at 16 19 27](https://user-images.githubusercontent.com/425211/101920896-aa368900-3bcc-11eb-9522-bec70d0466b6.png)

So it is a CORS (see https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) issue.

Please try setting the `baseURL` to `https://www.liberezvosressources.fr`.

Let me know, if that helps 👋🏻,
Jan

**Comment by Talisker69** [comment]
It works !!!
Thanks a lot

**Comment by janraasch** [comment]
I am glad I could help ☺️.

💁🏻‍♀️ Please consider supporting my work on this theme via PayPal (https://www.paypal.com/paypalme/janraasch/) or GitHub Sponsors (https://github.com/sponsors/janraasch) 💰.

Enjoy the holiday season 🎄, and stay safe 😷,
Jan
