### ISSUE TITLE
Fix activation of nav-items when each section is visited

### ISSUE THREAD

**Issue by sdelquin** [janraasch/hugo-scroll#18]
Depending on the size of each section, it is possible that the nav-item were not property activated.

For instance, see that "Services" is activated, but "About me" is not:
![screen-recording](https://user-images.githubusercontent.com/1591599/103015813-f8d31400-4538-11eb-832b-db04813f8e6e.gif)

I think it has to do with the decimals when doing calculations on .js

I propose to change the next line:
https://github.com/janraasch/hugo-scroll/blob/4d6f8a51e53b531e7169ea4162e19972da3de480/static/js/index.js#L95

For something like:
`if (w >= Math.floor(f) && w <= Math.ceil(b)) {`

**Comment by janraasch** [comment]
Hi @sdelquin, 

nice catch 👍. 

Would you mind opening a pr with your proposed changes so we could take that for a spin? 

Thank you and have a very merry Christmas 🎄 😁 👋,
Jan.
