### ISSUE TITLE
Contact nav-item is not activated

### ISSUE THREAD

**Issue by sdelquin** [janraasch/hugo-scroll#20]
Even when you scroll till the end of the page, contact nav-item is not activated:

![Captura de pantalla 2020-12-23 a las 21 18 36](https://user-images.githubusercontent.com/1591599/103037782-90019100-4564-11eb-8d24-95e045afed62.png)

**Comment by janraasch** [comment]
Fixed with https://github.com/janraasch/hugo-scroll/pull/21.
