### ISSUE TITLE
ForkAwesome

### ISSUE THREAD

**Issue by metbril** [janraasch/hugo-scroll#22]
Would you consider replacing the rather old FontAwesome 4.7 icons with the more recent ForkAwesome / accept a PR that replaces it?

https://forkaweso.me/Fork-Awesome/

For example, I could then use the Mastodon icon.

**Comment by janraasch** [comment]
Hi @metbril, 

that would be lovely. 

It is actually one of the things I wanted to do for a long time, but I never got around to do it 👌.

Cheers,
Jan

**Comment by metbril** [comment]
I'll try to find some time to prepare a PR

**Comment by janraasch** [comment]
Fixed with #23.
