### ISSUE TITLE
Deliver Google Fonts and jQuery locally

### ISSUE THREAD

**Issue by knodderdachs** [janraasch/hugo-scroll#34]
Hi!

I'd like it if the theme would deliver the Google Fonts and jQuery locally. You can change this manually in the source code, but I think it would be better if you could simply specify this via an option in config.toml.

Unfortunately, I don't know how to modify the source code to make it configurable.

The lines in question are 24 and 29 in head.html for the Google Fonts. jQuery is loaded in line 12 in baseof.html.

ATB
Torsten

**Comment by rkta** [comment]
To add on this:

This a German court ruling stating that using fonts served from google is at least problematic when you are a German:
https://rewis.io/urteile/urteil/lhm-20-01-2022-3-o-1749320/

May be @janraasch could change his mind. ;)

**Comment by rkta** [comment]
Thank you!
