### ISSUE TITLE
Question: How to include logo in header? 

### ISSUE THREAD

**Issue by gianwiher** [janraasch/hugo-scroll#35]
Hi
Great template! How can I add a custom logo above the header_headline? 
Thanks!

**Comment by janraasch** [comment]
Hi @gianwiher, thank you for reaching out 🤝 😁.

Sadly, 😅 there is currently to configuration option to do this.

Depending on your background / knowledge of html, you could overwrite the `index.html`-template locally and add any html / css you need yourself.

I hope that helps 🙏🏻 

Cheers!

**Comment by gianwiher** [comment]
Yes I tried exactly that but my basic understanding of html/css limited my success :sweat_smile:. I tried to reverse-engineer the syntax so I could specify an image in the `_index.md`-file but I am not quite there yet. Will need to go back to tutorials :upside_down_face:. 

Anyway, thank you for your answer, now I know that there is no out of the box feature that I am overlooking.
