### ISSUE TITLE
Footer should stick to bottom even if page is too short

### ISSUE THREAD

**Issue by passw0rd123** [janraasch/hugo-scroll#49]
If the content of the page is too short, the footer doesn't stay at the bottom of the browser window.

Your demo page does not have this short pages but you can reproduce this if you visit this [demo page](https://janraasch.github.io/hugo-scroll/services/) and reduce the zoom level to something like 30%.

I'm no expert on CSS but maybe something like this might help?

- [~~Stackoverflow - place footer at bottom only if page is "short"~~](https://stackoverflow.com/questions/21206058/place-footer-at-bottom-only-if-page-is-short)
- [Stackoverflow - **viewports**](https://stackoverflow.com/a/26090114)

**Comment by zjedi** [comment]
Not currently planned, sounds like a specific use case that may not be required by everyone. I'll be happy to accept it as an opt-in feature.
