### ISSUE TITLE
Extraneous </p> tags

### ISSUE THREAD

**Issue by damonlynch** [janraasch/hugo-scroll#7]
Hi Jan,

Thanks for your work on your great theme, which I'm really happy to use.

I'm very new to Hugo and my web skills are super rusty. Is this a bug in your theme? These are two examples of extraneous </p> tags, but there are others too. They are from the [demo](https://themes.gohugo.io/theme/hugo-scroll/).

![extraneous-p-tags](https://user-images.githubusercontent.com/1749868/92393231-9111ce00-f0ed-11ea-8df4-d8615573dd96.png)

As a total aside I'm building my site [here](https://damonlynch.net/). Only the home page is up so far, as I'm still working on the others. 

Thanks,
Damon

**Comment by janraasch** [comment]
Hi @damonlynch, thank you very much for reaching out 🥇 ❤️ .

Those `p`-tags actually were not needed. I removed them with https://github.com/janraasch/hugo-scroll/commit/9a7774bc4b67a52ce7e29f41263ae47f982425cf.

---

Also, thank you for posting the link to https://damonlynch.net/. Nice colors 👍 .

---

If your PhD-salary allows for a kindhearted sponsorship 🤓 😉, I’d also appreciate you supporting my open-source work through »GitHub sponsors« (recurring) or »PayPal« (one-time):

GitHub: https://github.com/sponsors/janraasch
PayPal: https://www.paypal.com/paypalme/janraasch/29,00

In any case, kind regards and keep up the good work 👋,
Jan

PS:

> rust web skills

I cannot decide if this should be the name of a nerdy cartoon character or simply a tagline to a video course on getting back into web development 😆 🤣 😉 😉 😉 .

**Comment by damonlynch** [comment]
Thanks for the quick fix, and thank you for your kind words. I just graduated and I am about to start looking for my first employment in some years. I'll make a donation but I can't afford €29 sorry. I have no job and no income at the moment! 😬😭

**Comment by janraasch** [comment]
Haha. No worries, no worries at all, Damon 😊.
