### ISSUE TITLE
Asterisk List Lighthouse Warning

### ISSUE THREAD

**Issue by aelfric** [janraasch/hugo-scroll#72]
When running a site generated from this theme through Google Lighthouse it gives a warning about the unordered list structure that it might be problematic for some screen readers because the span to render the icon is in between the list elements.  I have a small change to the template to render it in a compliant way. Are you open to a pull request for the change?

**Comment by zjedi** [comment]
@aelfric Hello, as a new maintainer, I'm reopening this for you to open a PR. We're intereted in reusable contributions.

**Comment by aelfric** [comment]
Thanks. Will clean up my change and make a PR tomorrow.
