### ISSUE TITLE
Non home pages lack style — feature, or needs work?

### ISSUE THREAD

**Issue by damonlynch** [janraasch/hugo-scroll#8]
Compared to the home page, additional pages are quite bare e.g. https://janraasch.github.io/hugo-scroll/services/

Obviously this is a question of taste, so that may be how you intend it to look. 

From my perspective, compared to the home page, the change in look is substantial. Personally, I'd like additional pages to look more like the home page. 

I guess that means I now need to learn how Hugo actually works 😃

**Comment by janraasch** [comment]
Hi @damonlynch, thank you for avidly contributing on this theme 👍🏻 .

This is a matter of taste, indeed. At this point, the simple design *is* feature. The reasoning is that the main page is the eye-catcher, and then the single pages are really more about providing detailed information. Thus, it's all about a nice reading experience - no design...

Again, a matter of taste...

Still, you can always overwrite the included template by creating your own `layouts/_default/single.html`-template. 

> Personally, I'd like additional pages to look more like the home page.

Are you able to describe this a little more precisely? E.g. do you want a header image? Different color sections? A menu on top?

Depending on how closely you want to resemble the homepage behavior, you could simply copy (parts of) the `layouts/index.html`-template included in this theme.

I hope that helps.

Cheers 👋🏻 ,
Jan

**Comment by janraasch** [comment]
No action here in about two weeks `#stale` 🧱 😃 .

I'll close this, since there is no actionable to be tackled.
